name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1 # or alternative dependency management
      - uses: php-actions/phpunit@v9

  PHP7_4:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install

      - name: Run PhPUnit
        run: ./test/phpunit/phpunit AllTests.php
